export const MenuData = [
	{
		name: 'Vegetable Samosa',
		image: '/assets/menu/paneer.jpg',
		price: 3.5,
		description: 'Triangular pastry stuffed with spiced cubed potatoes, green peas and garnished with greens.',
		spicy: false,
		glutenFree: false,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Appetizers',
	},
	{
		name: 'Chicken/Lamb Samosa',
		image: '/assets/menu/samosas.jpg',
		price: 3.5,
		description: 'Triangular pastry stuffed with chicken or lamb, rice, green peas, and garnished with greens.',
		spicy: false,
		glutenFree: false,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Appetizers',
	},
	{
		name: 'Pakoras',
		image: '/assets/menu/pakoras.jpg',
		price: 5.0,
		description:
			'Pakoras (gluten-free and vegan appetizer) are made with chickpeas flour, rice flour, spinach, and onions.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Appetizers',
	},
	{
		name: 'Plain Naan',
		image: '/assets/menu/naan.jpg',
		price: 2.99,
		description: 'Indian style plain naan garnished with cilantro.',
		spicy: false,
		glutenFree: false,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Naan',
	},
	{
		name: 'Garlic Naan',
		image: '/assets/menu/garlic-naan.jpg',
		price: 2.99,
		description: 'Naan stuffed with fresh garlic and garnished with cilantro.',
		spicy: false,
		glutenFree: false,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Naan',
	},
	{
		name: 'Gulab Jamun',
		image: '/assets/menu/gulab-jamun.jpg',
		price: 3.0,
		description: 'Made with milk powder and soaked in rose water cardamom syrup.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Mango Lassi',
		image: '/assets/menu/mango-lassi.jpg',
		price: 3.0,
		description: 'Mango pulp blend with homemade fresh yogurt.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Ras Malai',
		image: '/assets/menu/ras-malai.jpg',
		price: 5.99,
		description:
			'Ras Malai is flattened balls of cheese (paneer) soaked in malai (reduced milk) flavored with cardamon and saffron.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Kheer',
		image: '/assets/menu/kheer.jpg',
		price: 5.99,
		description: 'Kheer is Indian rice pudding made with rice , milk, cardamon, almonds, raisins and saffron. ',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Dal Makhni',
		image: '/assets/menu/dal-makhni.jpg',
		price: 11.99,
		description: 'A combination of black lentils flavored with spices and butter.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Saag Paneer',
		image: '/assets/menu/paneer.jpg',
		price: 12.99,
		description: 'Spinach and homemade fresh cheese cooked with onions, tomatoes, garlic, and creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},

	{
		name: 'Allo Saag',
		image: '/assets/menu/allo-saag.jpg',
		price: 11.99,
		description: 'Delightful combinations of potatoes and spinach cooked with fresh spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chana Masala',
		image: '/assets/menu/chana-masala.jpg',
		price: 11.99,
		description: 'Chickpeas cooked in tomatoes, ginger, garlic creamy gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},

	{
		name: 'Vegetable Biryani',
		image: '/assets/menu/veg-biryani.jpg',
		price: 11.99,
		description: 'All fresh vegetables cooked with basmati rice and fresh spices',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Mutter Paneer',
		image: '/assets/menu/mutter-paneer.jpg',
		price: 12.99,
		description: 'Fresh homemade Paneer and green peas cooked with ginger, garlic creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Mutter Mushroom',
		image: '/assets/menu/mutter-mushroom.jpg',
		price: 12.99,
		description: 'Fresh Mushroom and green peas cooked in ginger, garlic, tomatoes, and creamy gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},

	{
		name: 'Malai Kofta',
		image: '/assets/menu/malai-kofta.jpg',
		price: 12.99,
		description: 'Potatoes and homemade cheese balls cooked in smooth rich and creamy gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Navratan Curry',
		image: '/assets/menu/navratan-curry.jpg',
		price: 12.99,
		description:
			'Fresh Vegetable (carrot, cauliflower, peas, corn, mushroom, peppers, potaoes, brocolli) cooked in ginger garlic creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Shahi Paneer Korma',
		image: '/assets/menu/shahi-paneer-korma.jpg',
		price: 13.99,
		description: 'Homemade paneer cooked with onion and tomato creamy sauce with cashew paste.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: true,
		category: 'Mains',
	},
	{
		name: 'Allo Mutter',
		image: '/assets/menu/allo-mutter.jpg',
		price: 11.99,
		description: 'Potatoes and peas cooked with fresh spices and ginger, garlic, tomatoes, onion sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Curry',
		image: '/assets/menu/chicken-curry.jpg',
		price: 12.99,
		description: 'Boneless chicken cooked in a mild gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Butter Chicken',
		image: '/assets/menu/butter-chicken.jpg',
		price: 13.99,
		description: 'Boneless chicken cooked with cashews, butter and ginger , garlic creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: true,
		category: 'Mains',
	},
	{
		name: 'Chicken Tikka Masala',
		image: '/assets/menu/chicken-tikka-masala.jpg',
		price: 12.99,
		description:
			'Boneless chicken marinated with yogurt and fresh spices and cooked in ginger, garlic, creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Saag',
		image: '/assets/menu/chicken-saag.jpg',
		price: 12.99,
		description: 'Boneless Chicken cooked with spinach and creamy gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Vindaloo',
		image: '/assets/menu/chicken-vindaloo.jpg',
		price: 13.99,
		description: 'Boneless Chicken cooked in a ​spicy sauce with potatoes.',
		spicy: true,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Biryani',
		image: '/assets/menu/chicken-biryani.jpg',
		price: 12.99,
		description: 'Boneless Chicken cooked with basmati rice and spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Dopiaza',
		image: '/assets/menu/chicken-dopiaza.jpg',
		price: 13.99,
		description: 'Boneless Chicken cooked with onions, and bell peppers.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Saag',
		image: '/assets/menu/lamb-saag.jpg',
		price: 13.99,
		description: 'Boneless lamb cooked with spinach and creamy gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Dopaiza',
		image: '/assets/menu/lamb-dopaiza.jpg',
		price: 13.99,
		description: 'Thinly sliced lamb cooked with onions and bell peppers.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Vindaloo',
		image: '/assets/menu/lamb-vindaloo.jpg',
		price: 13.99,
		description: 'Boneless lamb cooked with potatoes in spicy sauce.',
		spicy: true,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Biryani',
		image: '/assets/menu/lamb-biryani.jpg',
		price: 13.99,
		description: 'Boneless lamb cooked with basmati rice and spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Curry',
		image: '/assets/menu/lamb-curry.jpg',
		price: 13.99,
		description: 'Boneless Lamb cooked in mild gravy.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Basmati rice',
		image: '/assets/menu/basmati.jpg',
		price: 2.99,
		description: 'Plain basmati rice.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	{
		name: 'Jeera rice',
		image: '/assets/menu/jeera-rice.jpg',
		price: 3.99,
		description: 'Basmati rice cooked with cumin tampring.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	{
		name: 'Veggie Schezwan rice',
		image: '/assets/menu/veggie-schezwan-rice.jpg',
		price: 8.99,
		description:
			'Schezwan fried rice is a vegetarian and vegan stir-fried rice that has bold and spicy homemade schezwan sauce loaded with healthy mix vegetables, aromatics and herbs.',
		spicy: true,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	{
		name: 'Onion Salad',
		image: '/assets/menu/onion-salad.jpg',
		price: 2.99,
		description: 'Thinly sliced onion rings, lemon, green chili, cilantro and spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	// {
	// 	name: 'Extra paneer, vegetable and chicken',
	// 	image: '/assets/menu/paneer.jpg',
	// 	price: 2.0,
	// 	description: 'Add extra paneer, or chicken or vegetable in any dish.',
	// 	spicy: false,
	// 	glutenFree: true,
	// 	vegetarian: false,
	// 	vegan: false,
	// 	nuts: false,
	// 	category: 'Sides',
	// },
];
