export const MenuData = [
	{
		name: 'Vegetable Samosa',
		image: '/assets/menu/paneer.jpg',
		price: 3.5,
		description: 'Crispy golden pastry triangles filled with spiced potatoes, green peas, and fresh herbs. A classic vegetarian favorite.',
		spicy: false,
		glutenFree: false,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Appetizers',
	},
	{
		name: 'Chicken or Lamb Samosa',
		image: '/assets/menu/samosas.jpg',
		price: 3.5,
		description: 'Flaky pastry stuffed with your choice of chicken or lamb, blended with peas, rice, and aromatic spices.',
		spicy: false,
		glutenFree: false,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Appetizers',
	},
	{
		name: 'Pakoras',
		image: '/assets/menu/pakoras.jpg',
		price: 5.0,
		description: 'Crispy chickpea and rice flour fritters tossed with spinach and onions, fried to golden perfection. Naturally gluten-free and vegan.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Appetizers',
	},
	{
		name: 'Plain Naan',
		image: '/assets/menu/naan.jpg',
		price: 2.99,
		description: 'Soft and fluffy flatbread, brushed with butter and finished with fresh cilantro.',
		spicy: false,
		glutenFree: false,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Naan',
	},
	{
		name: 'Garlic Naan',
		image: '/assets/menu/garlic-naan.jpg',
		price: 2.99,
		description: 'Naan infused with roasted garlic, brushed with butter and sprinkled with cilantro.',
		spicy: false,
		glutenFree: false,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Naan',
	},
	{
		name: 'Gulab Jamun',
		image: '/assets/menu/gulab-jamun.jpg',
		price: 3.0,
		description: 'Soft milk dumplings soaked in warm rose and cardamom syrup.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Mango Lassi',
		image: '/assets/menu/mango-lassi.jpg',
		price: 3.0,
		description: 'A cool and creamy blend of ripe mango pulp and homemade yogurt that is sweet, tangy, and refreshing.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Ras Malai',
		image: '/assets/menu/ras-malai.jpg',
		price: 5.99,
		description: 'Soft paneer patties soaked in sweet saffron-infused milk with a hint of cardamom.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Dessert',
	},
	{
		name: 'Kheer',
		image: '/assets/menu/kheer.jpg',
		price: 5.99,
		description: 'Traditional Indian rice pudding slow-cooked with milk, cardamom, and saffron then topped with almonds and raisins.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: true,
		category: 'Dessert',
	},
	{
		name: 'Dal Makhni',
		image: '/assets/menu/dal-makhni.jpg',
		price: 11.99,
		description: 'Black lentils slow-cooked with aromatic spices, butter and cream.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Saag Paneer',
		image: '/assets/menu/paneer.jpg',
		price: 12.99,
		description: 'Fresh spinach and homemade paneer cubes simmered with onions, garlic and tomatoes in a creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Aloo Saag',
		image: '/assets/menu/allo-saag.jpg',
		price: 11.99,
		description: 'Tender potatoes and fresh spinach cooked with traditional spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chana Masala',
		image: '/assets/menu/chana-masala.jpg',
		price: 11.99,
		description: 'Chickpeas simmered in a spiced tomato, ginger, and garlic sauce with aromatics.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Vegetable Biryani',
		image: '/assets/menu/veg-biryani.jpg',
		price: 11.99,
		description: 'Aromatic basmati rice cooked with mixed vegetables, herbs and whole spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Mutter Paneer',
		image: '/assets/menu/mutter-paneer.jpg',
		price: 12.99,
		description: 'Paneer cubes and green peas simmered in a creamy tomato, ginger and garlic sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Mutter Mushroom',
		image: '/assets/menu/mutter-mushroom.jpg',
		price: 12.99,
		description: 'Fresh mushrooms and green peas cooked in a spiced tomato and onion sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Malai Kofta',
		image: '/assets/menu/malai-kofta.jpg',
		price: 12.99,
		description: 'Golden potato and paneer dumplings simmered in a luxurious, creamy tomato-cashew sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: true,
		category: 'Mains',
	},
	{
		name: 'Navratan Curry',
		image: '/assets/menu/navratan-curry.jpg',
		price: 12.99,
		description: 'A royal curry made with a medley of nine vegetables, simmered in a mild, creamy sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Shahi Paneer Korma',
		image: '/assets/menu/shahi-paneer-korma.jpg',
		price: 13.99,
		description: 'Paneer cubes in a rich, velvety sauce made with cashews, cream, and aromatic spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: true,
		category: 'Mains',
	},
	{
		name: 'Aloo Mutter',
		image: '/assets/menu/allo-mutter.jpg',
		price: 11.99,
		description: 'Potatoes and peas simmered with onions, tomatoes and spices in a flavorful curry.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Curry',
		image: '/assets/menu/chicken-curry.jpg',
		price: 12.99,
		description: 'Boneless chicken cooked in a mildly spiced, flavorful curry sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Butter Chicken',
		image: '/assets/menu/butter-chicken.jpg',
		price: 13.99,
		description: 'Succulent chicken cooked in a creamy tomato-cashew sauce, finished with butter.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: true,
		category: 'Mains',
	},
	{
		name: 'Chicken Tikka Masala',
		image: '/assets/menu/chicken-tikka-masala.jpg',
		price: 12.99,
		description: 'Boneless chicken marinated in yogurt and spices, cooked in a smoky, creamy tomato sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Saag',
		image: '/assets/menu/chicken-saag.jpg',
		price: 12.99,
		description: 'Tender chicken simmered with spinach in a creamy, spiced curry sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Vindaloo',
		image: '/assets/menu/chicken-vindaloo.jpg',
		price: 13.99,
		description: 'A fiery Goan specialty, chicken simmered in a hot and tangy sauce with tender potatoes.',
		spicy: true,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Biryani',
		image: '/assets/menu/chicken-biryani.jpg',
		price: 12.99,
		description: 'Fragrant basmati rice layered with spiced chicken and herbs, cooked to perfection.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Chicken Dopiaza',
		image: '/assets/menu/chicken-dopiaza.jpg',
		price: 13.99,
		description: 'Boneless chicken cooked with onions two ways, caramelized and fresh, along with peppers and spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Saag',
		image: '/assets/menu/lamb-saag.jpg',
		price: 13.99,
		description: 'Juicy lamb simmered with spinach in a rich, creamy curry sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Dopiaza',
		image: '/assets/menu/lamb-dopaiza.jpg',
		price: 13.99,
		description: 'Tender lamb cooked with onions and peppers in a flavorful curry sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Vindaloo',
		image: '/assets/menu/lamb-vindaloo.jpg',
		price: 13.99,
		description: 'Bold and spicy Goan lamb curry simmered with tangy sauce and tender potatoes.',
		spicy: true,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Biryani',
		image: '/assets/menu/lamb-biryani.jpg',
		price: 13.99,
		description: 'Aromatic basmati rice cooked with spiced lamb, herbs, and whole spices.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Lamb Curry',
		image: '/assets/menu/lamb-curry.jpg',
		price: 13.99,
		description: 'Tender lamb pieces simmered in a gently spiced curry sauce.',
		spicy: false,
		glutenFree: true,
		vegetarian: false,
		vegan: false,
		nuts: false,
		category: 'Mains',
	},
	{
		name: 'Basmati Rice',
		image: '/assets/menu/basmati.jpg',
		price: 2.99,
		description: 'Steamed, fluffy basmati rice — light, fragrant, and perfect with any curry.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	{
		name: 'Jeera Rice',
		image: '/assets/menu/jeera-rice.jpg',
		price: 3.99,
		description: 'Fragrant basmati rice tempered with toasted cumin seeds for a nutty aroma and flavor.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	{
		name: 'Veggie Schezwan Rice',
		image: '/assets/menu/veggie-schezwan-rice.jpg',
		price: 8.99,
		description: 'Indo-Chinese style fried rice tossed with vegetables, garlic, and a spicy homemade Schezwan sauce.',
		spicy: true,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
	{
		name: 'Onion Salad',
		image: '/assets/menu/onion-salad.jpg',
		price: 2.99,
		description: 'Fresh onion rings tossed with lemon, green chili, cilantro, and a sprinkle of spices for a crisp, zesty bite.',
		spicy: false,
		glutenFree: true,
		vegetarian: true,
		vegan: true,
		nuts: false,
		category: 'Sides',
	},
];
